class CardMap:
    @staticmethod
    def getCardFileName(card: int) -> str:
        cardMap = {
            0: 'images/Playing_card_club_A.png',
            1: 'images/Playing_card_club_2.png',
            2: 'images/Playing_card_club_3.png',
            3: 'images/Playing_card_club_4.png',
            4: 'images/Playing_card_club_5.png',
            5: 'images/Playing_card_club_6.png',
            6: 'images/Playing_card_club_7.png',
            7: 'images/Playing_card_club_8.png',
            8: 'images/Playing_card_club_9.png',
            9: 'images/Playing_card_club_10.png',
            10: 'images/Playing_card_club_J.png',
            11: 'images/Playing_card_club_Q.png',
            12: 'images/Playing_card_club_K.png',

            13: 'images/Playing_card_diamond_A.png',
            14: 'images/Playing_card_diamond_2.png',
            15: 'images/Playing_card_diamond_3.png',
            16: 'images/Playing_card_diamond_4.png',
            17: 'images/Playing_card_diamond_5.png',
            18: 'images/Playing_card_diamond_6.png',
            19: 'images/Playing_card_diamond_7.png',
            20: 'images/Playing_card_diamond_8.png',
            21: 'images/Playing_card_diamond_9.png',
            22: 'images/Playing_card_diamond_10.png',
            23: 'images/Playing_card_diamond_J.png',
            24: 'images/Playing_card_diamond_Q.png',
            25: 'images/Playing_card_diamond_K.png',

            26: 'images/Playing_card_heart_A.png',
            27: 'images/Playing_card_heart_2.png',
            28: 'images/Playing_card_heart_3.png',
            29: 'images/Playing_card_heart_4.png',
            30: 'images/Playing_card_heart_5.png',
            31: 'images/Playing_card_heart_6.png',
            32: 'images/Playing_card_heart_7.png',
            33: 'images/Playing_card_heart_8.png',
            34: 'images/Playing_card_heart_9.png',
            35: 'images/Playing_card_heart_10.png',
            36: 'images/Playing_card_heart_J.png',
            37: 'images/Playing_card_heart_Q.png',
            38: 'images/Playing_card_heart_K.png',

            39: 'images/Playing_card_spade_A.png',
            40: 'images/Playing_card_spade_2.png',
            41: 'images/Playing_card_spade_3.png',
            42: 'images/Playing_card_spade_4.png',
            43: 'images/Playing_card_spade_5.png',
            44: 'images/Playing_card_spade_6.png',
            45: 'images/Playing_card_spade_7.png',
            46: 'images/Playing_card_spade_8.png',
            47: 'images/Playing_card_spade_9.png',
            48: 'images/Playing_card_spade_10.png',
            49: 'images/Playing_card_spade_J.png',
            50: 'images/Playing_card_spade_Q.png',
            51: 'images/Playing_card_spade_K.png',
        }
        fileName = cardMap[card]
        return fileName
